### PR TITLE
Issue 40/fix installer

### PR DESCRIPTION
**Pull request by torresashjian**
Merge into develop to be included in v0.1.2

- Moved installation docs to documentation page.
- Created the install.sh script that will be used to install the cli, this does not run the tests, just install the cli.

### CODE REVIEW

**Comment by yxuco** [comment]
Looks good.  I am ok to remove the install instructions, although it would be helpful for developers to see a simple installation instruction in the README, instead of referring to the other doc.

**Comment by torresashjian** [comment]
Yes I agree but we have to decide to:
1.- Duplicate the instructions
2.- Have it just in the docs
3.- Have it just in the readme

Maybe we can start by having it just in the docs, and create a script to duplicate them but with an automated script. Sounds good?

**Comment by yxuco** [comment]
I think it should be OK to let developer to use Makefile with instructions in README.md, which is typically what many open source projects do.  The curl approach in the other doc can be used by other non-developers, which could have its own script that does not use normal GOPATH and makefile, and so it can be different from the instructions in README.

**Comment by torresashjian** [comment]
Actually, You are right. The best solution is to have:
1.- An installer for the latest version in the docs and
2.- A build from source section in the Readme.

I'll create an issue, and I can take care of it.

In fact the installer still not good since it will not be locked to a specific revision.

**Pull request merged**
